apps/goodfood/urls.py
from django.urls import path
from apps.goodfood import views
 
app_name = "goodfood"


urlpatterns = [path("", views.IndexView.as_view(), name="main"),
               path("food/", views.FoodListView.as_view(), name="goods"),
               path("food/<slug:slug_name>/<int:pk>", views.FoodDetailView.as_view(), name="_detail"),
               path("food/<int:cat_id>", views.FoodCategoryView.as_view(), name="_category")
               ]


apps/users/urls.py
from django.urls import path, include



urlpatterns = [
    path('accounts/', include('allauth.urls')),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.goodfood.urls")),
    path('', include("apps.users.urls")),

] 

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
    path("__debug__/", include(debug_toolbar.urls)),
    ]






apps/goodfood/models.py
from slugify import slugify

from django.db import models
from django.urls import reverse
from django.core.validators import  MinLengthValidator, MaxLengthValidator, RegexValidator

from apps.goodfood.validators import GoodfoodValidator





# Create your models here.
class Categories(models.Model):
  
  cat = models.CharField(verbose_name='категория', max_length=32, db_index=True, validators=[MinLengthValidator(1), MaxLengthValidator(32), GoodfoodValidator()])
    
  class Meta:
      verbose_name = ('Категория')
      verbose_name_plural = ('Категории')
      
  def __str__(self): 
    return self.cat    
      
      
  def get_absolute_url(self):
     return reverse('goodfood:_category', kwargs={'cat_id': self.pk})


class Goods(models.Model):
  
  name = models.CharField(
    verbose_name='Название', max_length=64, db_index=True, editable=True, validators=[MinLengthValidator(1), MaxLengthValidator(64),  GoodfoodValidator()]
    )
  
  photo = models.ImageField(
    verbose_name='Фото', name='photo',
    blank=False, null=False, editable=True,
    )
  
  description = models.TextField(
    verbose_name='Описание', name='desc', max_length=256, unique=False, blank=True, null=True, editable=True, validators=[MinLengthValidator(1), MaxLengthValidator(256), GoodfoodValidator()]
  )
  
  category = models.ForeignKey(to=Categories, verbose_name='категория', name='category', on_delete=models.PROTECT)
  
  
  slugify_name = models.SlugField(max_length=256, blank=True, unique=True, allow_unicode=True, verbose_name="Слаг", validators=[
            RegexValidator(
                regex=r'^[-a-zA-Z0-9_]+$',
                message='Slug может содержать только буквы, цифры, дефис и подчёркивания.'
            )
        ])
  
  time_created = models.DateTimeField(verbose_name='Время создания', auto_now_add=True, editable=False )
  time_updated = models.DateTimeField(verbose_name='Время изменения', auto_now=True, editable=True)
   
  
  class Meta:
      verbose_name = ('Товар')
      verbose_name_plural = ('Товары')

      db_table_comment = 'База данных с рецептами блюд'

      ordering = ['-time_created']

      #The name of a field or a list of field names in the model, typically DateField, DateTimeField, or IntegerField. 
      #This specifies the default field(s) to use in your model Manager’s latest() and earliest() methods.
      get_latest_by = ['time_updated']

      # разрешения для тех кто может добавлять, редактировать, изменять - https://docs.djangoproject.com/en/5.2/ref/models/options/#permissions
      # permissions = [()]

  def __str__(self):
      return self.name
  
  def save(self, *args, **kwargs):
    if not self.slugify_name:
      self.slugify_name = slugify(self.name)
    super(Goods, self).save(*args, **kwargs)
    

  def get_absolute_url(self):
     return reverse("goodfood:_detail", kwargs={"slug_name": self.slugify_name, "pk": self.pk})
      





apps/users/forms.py
from django import forms

from allauth.account.forms import LoginForm
from allauth.account.forms import SignupForm

class CustomLoginForm(LoginForm):
    login = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Имя пользователя или Email',
        }),
        label="Логин"
    )

    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Пароль',
        }),
        label="Пароль"
    )

    remember = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        label="Запомнить меня"
    )
    


class CustomSignupForm(SignupForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Имя пользователя',
        }),
        label="Имя пользователя"
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Email',
        }),
        label="Email"
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Пароль',
        }),
        label="Пароль"
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Подтверждение пароля',
        }),
        label="Подтвердите пароль"
    )

apps/goodfood/views.py
from django.shortcuts import redirect, render, get_object_or_404, get_list_or_404
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, TemplateView




from .models import Goods
from .mixins import SearchMixin 

# Настроить более точное кеширование отдельно темплейты и view

class IndexView(TemplateView):
    template_name = "goodfood/index.html"


class FoodListView(SearchMixin, ListView):
    model = Goods
    template_name = "goodfood/goods.html"
    context_object_name = "context"
    paginate_by = 12  




@method_decorator(cache_page(300), name='dispatch')
class FoodDetailView(DetailView):
    model = Goods
    template_name = "goodfood/food.html"
    context_object_name = "food"

    slug_field = "slugify_name"
    slug_url_kwarg = "slug_name"
    pk_url_kwarg = "pk"

    def get_object(self):
        pk = self.kwargs.get("pk")
        slug = self.kwargs.get("slug_name")
        return get_object_or_404(Goods, pk=pk, slugify_name=slug)

@method_decorator(cache_page(300), name='dispatch')
class FoodCategoryView(ListView):
    model = Goods
    template_name = "goodfood/category.html"
    context_object_name = "food"

    def get_queryset(self):
        cat_id = self.kwargs.get("cat_id")
        return get_list_or_404(Goods.objects.filter(category_id=cat_id))

# views_handlers
def page_not_found(request, exception):
    return render(request, "handlers/page_404.html", status=404, context={"e": exception}) 

def error_R(request):
    return render(request, "handlers/page_500.html", status=500)




  
  
  

  

apps/goodfood/templates/category.html
{% extends "base.html" %} {% block content %}

		<div class="second-block">
			{% for f in food %}
				<ul class="content-food-list">
				<li><div class="category-food">{{f.category}}</div></li>

				<li><div class="title-food"><a href="{{ f.get_absolute_url }}">{{f.name}}</a></div></li>
				<li><div class="text-food">{{f.desc}}</div></li>
				<li><div class="img-food"><img src="{{ MEDIA_URL }}/{{f.photo}}" alt="" /></li>
				</ul>
			{% endfor %}
			</div>
		</div>
	{% endblock content %}
</html>

apps/goodfood/templates/food.html
{% extends "base.html" %} {% load static %} {% block content %}

<div class="second-block">

		<ul class="content-food-list">
		<li><div class="category-food"><a href="{{f.category.get_absolute_url}}">{{f.category}}</a></div></li>
		<li><div class="title-food">{{f.name}}</div></li>
		<li><div class="text-food">{{f.desc}}</div></li>
		<li><div class="img-food"><img src="{{ MEDIA_URL }}/{{f.photo}}" alt="" /></li>
		</ul>

	</div>
</div>
	{% endblock content %}
</html>

apps/goodfood/templates/goodfood/category.html
{% extends "base.html" %} 
{% load static %} 

{% block content %}

<section class="second-block">
<div class="container my-5">
  <div class="row g-4">
    {% for f in food %}
      <div class="col-12 col-sm-6 col-md-4 col-lg-3">
        <article class="card h-100 d-flex flex-column">
        {% if f.category %}
          <span class="badge bg-success mt-2 ms-2 position-absolute top-0 start-0">{{ f.category }}</span>
        {% endif %}

        {% if f.photo %}
        <div class="card-img-wrapper">
          <img src="{{ MEDIA_URL }}{{ f.photo }}" alt="{{ f.name }}" draggable="false">
        </div>
        {% endif %}

        <div class="card-body d-flex flex-column text-center">
          <h5 class="card-title mb-2">{{ f.name }}</h5>
          <p class="card-text scroll-text mb-3">{{ f.desc }}</p>
          
         
          <a href="{{ f.get_absolute_url }}" class="btn btn-primary mt-auto">Посмотреть</a>
        </div>
      </article>
      </div>
    {% endfor %}
  </div>
</div>
</section>


{% endblock content %}

apps/goodfood/templates/goodfood/food.html
{% extends "base.html" %} {% load static %} 



{% block content %}
<section class="second-block">
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <div class="card shadow-lg">

        {% if food.category %}
          <span class="badge bg-success mt-2 ms-2 position-absolute top-0 start-0"><a href="{{food.category.get_absolute_url}}">{{ food.category }}</a></span>
        {% endif %}
        
        <!-- Картинка блюда -->
        {% if food.photo %}
        <img src="{{ MEDIA_URL }}{{ food.photo }}" class="card-img-top img-fluid" alt="{{ food.photo }}" draggable="false">
        {% endif %}

        <div class="card-body">
          <!-- Название -->
          <h2 class="card-title">{{ food.name }}</h2>


          <!-- Описание -->
          <p class="card-text scroll-text">{{ food.desc }}</p>

          <!-- Дополнительно можно добавить поля: цена, ингредиенты -->
          {% if food.price %}
          <p class="fw-bold">Цена: {{ food.price }} ₽</p>
          {% endif %}

          <!-- Кнопка возврата -->
          <a href="{% url 'goodfood:goods' %}" class="btn btn-outline-primary mt-3">Вернуться к списку</a>
        </div>
      </div>
    </div>
  </div>
</div>
</section>
{% endblock content %}

apps/goodfood/templates/goodfood/goods.html
{% extends "base.html" %} {% load static cache %} 

{% block content %}

<form method="get" class="search-form">
  {% csrf_token %}
  <input type="text" name="q" placeholder="Поиск..." value="{{ request.GET.q }}">
  <button type="submit">🔍</button>
</form>
{% cache 600 "list_page" %}
<section class="second-block">
<div class="container my-5">
  <div class="row g-4">
    {% for food in context %}
      <div class="col-12 col-sm-6 col-md-4 col-lg-3">
        <article class="card h-100 d-flex flex-column">
        {% if food.category %}
          <span class="badge bg-success mt-2 ms-2 position-absolute top-0 start-0"><a href="{{food.category.get_absolute_url}}">{{ food.category }}</a></span>
        {% endif %}

        {% if food.photo %}
        <div class="card-img-wrapper">
          <img src="{{ MEDIA_URL }}{{ food.photo }}" alt="{{ food.name }}" draggable="false">
        </div>
        {% endif %}

        <div class="card-body d-flex flex-column text-center">
          <h5 class="card-title mb-2">{{ food.name }}</h5>
          <p class="card-text scroll-text mb-3">{{ food.desc }}</p>
          
         
          <a href="{{ food.get_absolute_url }}" class="btn btn-primary mt-auto">Посмотреть</a>
        </div>
      </article>
      </div>
    {% endfor %}

  </div>
</div>
</section>
{% endcache %}



{% endblock content %}



apps/goodfood/templates/goodfood/index.html
{% extends "base.html" %}{% load static %}{% load cache %}

{% block content %}
  {% cache 1800 index_page  %}
    <div class="main-block">
      <div class="container">
        <div class="row justify-content-start">
          <div class="col-12 col-md-8">
            <h1 class="title">Правильные ингридиенты для правильных блюд</h1>
            <div class="btts d-flex flex-wrap gap-3 justify-content-start justify-content-md-start">
              <button type="button" class="done">Забронировать</button>
              <button type="button" class="look-at-menu">
                <a class="btn-link" href="{% url 'goodfood:goods'%}">Посмотреть меню</a>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endcache %}
{% endblock content %}


apps/goodfood/templates/goods.html
{% extends "base.html" %} {% load static %} {% block content %}

		
		<div class="second-block">

				{% for food in context %}			
				<ul class="content-food-list">

					{% if food.category %}
					<li><div class="category-food"><a href="{{food.category.get_absolute_url}}">{{food.category}}</a></div></li>
					{% endif %}
	
					{% if food.name %}
					<li><div class="title-food"><a href="{{food.get_absolute_url}}">{{food.name}}</a></div></li>
					{% endif %}

					{% if food.desc %}		
					<li><div class="text-food">{{food.desc}}</div></li>
					{% endif %}

					{% if food.photo %}
					<li><div class="img-food">
						<img src="{{ MEDIA_URL }}/{{food.photo}}" alt="" />
					</li>
					{% endif %}
				</ul>
				{% endfor %}
			</div>
		</div>

	{% endblock content %}

apps/goodfood/templates/handlers/page_404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>404</title>
</head>
<body>
    <h1>Страница не найдена</h1>
        <h2>Error 404 traceback: </h2> <h5>{{e}}</h5>
</body>
</html>

apps/goodfood/templates/handlers/page_500.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    ERRROR
    
</body>
</html>

apps/goodfood/templates/index.html
{% extends "base.html" %}{% load static %}{% block content %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="{% static 'css/styles.css' %}" />
		<title>{% block title %} Document {% endblock title %}</title>
	</head>
	<body>
		<div class="main-block">
			<!-- <div class="nav-bar">
				<div class="nav-menu">
					<div class="icon">
						<a href="#" class="nav-link"
							><img src="{% static 'images/logo.png' %}" alt=""
						/></a>
					</div>
					<ul>
						<li><a href="#" class="nav-link">Проект</a></li>
						<li><a href="#" class="nav-link">Адрес</a></li>
						<li>
							<a href="{% url 'goodfood:main' %}" class="nav-link">Главная</a>
						</li>
					</ul>
				</div>
			</div> -->

			<div class="content">
				<div class="title">Правильные ингридиенты для правильных блюд</div>
				<div class="btts">
					<button type="button" class="done">Забронировать</button>
					<button type="button" class="look-at-menu">
						<a class="btn-link" href="{% url 'goodfood:goods'%}"
							>Посмотреть меню</a
						>
					</button>
				</div>
			</div>
		</div>
	</body>
</html>

{% endblock content %}

goodfood/templates/login.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}
{% load socialaccount %}  

{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 80vh;">
  <div class="card shadow p-4" style="max-width: 400px; width: 100%;">
    <h2 class="text-center mb-4">вход</h2>

    <form method="post" action="{% url 'account_login' %}">
        {% csrf_token %}
        
        <div class="d-grid mb-3 w-100">
            <label for="id_login">Email или Username</label>
            {{ form.username }}
            {% if form.username.errors %}
                <div class="text-danger small">{{ form.username.errors }}</div>
            {% endif %}
        </div>

        <div class="d-grid mb-3 w-100">
            <label for="id_password">Пароль</label>
            {{ form.password }}
            {% if form.password.errors %}
                <div class="text-danger mx-auto">{{ form.password.errors }}</div>
            {% endif %}
        </div>

        <button type="submit" class="btn btn-primary d-grid w-100">Войти</button>
    </form>

    <p class="mt-3 text-center">или</p>

    <div class="d-grid w-100">
  <a href="{% provider_login_url 'google' %}" class="btn btn-danger">
    <i class="bi bi-google me-2"></i> Войти через Google
  </a>
</div>

    <div class="mt-3 text-center">
        <p>Нет аккаунта? <a href="{% url 'account_signup' %}">Зарегистрироваться</a></p>
        <p><a href="{% url 'account_reset_password' %}">Забыли пароль?</a></p>
    </div>
</div>
</div>
</div>
{% endblock %}

goodfood/templates/registration.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}
{% load socialaccount %}  
{% load i18n %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 80vh;">
  <div class="card shadow p-4" style="max-width: 400px; width: 100%;">
    <h2 class="text-center mb-4">Регистрация</h2>

    <form method="post" action="{% url 'account_signup' %}">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <div class="d-grid mb-3 w-100">
      {{form.username}}
      </div>
      <div class="d-grid mb-3 w-100">
      {{form.email}}
      </div>
      <div class="d-grid mb-3 w-100">
      {{form.password1}}
      </div>
      <div class="d-grid mb-3 w-100">
      {{form.password2}}
      </div>
          {% for error in field.errors %}
            <div class="invalid-feedback d-block">{{ error }}</div>
          {% endfor %}
      <button type="submit" class="btn btn-success w-100">Зарегистрироваться</button>
    </form>

    <p class="mt-3 text-center">или</p>

    <div class="text-center">
      <a href="{% provider_login_url 'google' %}" class="btn btn-danger w-100">Войти через Google</a>
    </div>

    <p class="text-center mt-3">
      Уже есть аккаунт?
      <a href="{% url 'account_login' %}">Войти</a>
    </p>
  </div>
</div>
{% endblock %}

templates/base.html
{% load static cache %}

{% load socialaccount %}

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  <title>{% block title %} Document {% endblock title %}</title>
</head>
<body>

{% cache 1800 navbar %}
<nav class="navbar navbar-expand-lg nav-bar">
  <div class="container-fluid nav-menu">

    <a class="navbar-brand icon" href="{% url 'goodfood:main' %}">
      <img src="{% static 'images/logo.png' %}" alt="logo" width="80">
    </a>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNav">
      <span class="navbar-toggler-icon"></span>
    </button>

    
      


    <div class="collapse navbar-collapse" id="mainNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item"><a href="#" class="nav-link">Проект</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Адрес</a></li>
        {% endcache %}
        
        {% if request.user.is_authenticated %}

        
         <li class="nav-item">
          <form method="post" action="{% url 'account_logout' %}">
            {% csrf_token %}
            <button type="submit" class="nav-link">Выход</button>
          </form>
        </li>
        {% else %}
        <li class="nav-item"><a href="{% url 'account_login' %}" class="nav-link">Вход</a></li>

        <li class="nav-item"><a href="{% url 'account_signup' %}" class="nav-link">Регистрация</a></li>
        {% endif %}
        
      </ul>
    </div>
  </div>
</nav>

{% block content %} {% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
</body>

templates/base_auth.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Аккаунт{% endblock %}</title>

    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100">

<div class="flex justify-center mt-20">
    <div class="w-full max-w-md bg-white p-8 rounded-xl shadow">
        {% block content %}{% endblock %}
    </div>
</div>

</body>
</html>